# Generated by Django 6.0.3 on 2026-03-26 01:39

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short title shown in the notification header.', max_length=200)),
                ('body', models.TextField(help_text='Full alert message body displayed when the user opens the alert.')),
                ('category', models.CharField(choices=[('security', 'Security'), ('health', 'Health'), ('academic', 'Academic'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('urgency', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, help_text='Urgency level assigned by the classification pipeline.', max_length=10)),
                ('classification_method', models.CharField(choices=[('keyword_override', 'Keyword Override'), ('xgboost', 'XGBoost')], help_text='Whether urgency was assigned via keyword override or XGBoost.', max_length=20)),
                ('classification_confidence', models.FloatField(blank=True, help_text='XGBoost prediction confidence (0–1). None for keyword override.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('classified', 'Classified'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], db_index=True, default='classified', help_text='Lifecycle status. Set to DISPATCHED by the Celery delivery task.', max_length=15)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When the Celery task finished dispatching this alert.', null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Total number of users this alert was sent to.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False if the alert has been retracted by an administrator.')),
                ('created_by', models.ForeignKey(help_text='The administrator account that composed and submitted this alert.', on_delete=django.db.models.deletion.PROTECT, related_name='alerts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('lan_websocket', 'LAN WebSocket'), ('offline_stored', 'Offline (stored on device)')], db_index=True, max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the backend confirmed delivery via this channel.', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the user tapped Acknowledge on a Critical/High full-screen alert.', null=True)),
                ('fcm_message_id', models.CharField(blank=True, default='', help_text='Firebase message ID for FCM deliveries (for debugging).', max_length=200)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['urgency', 'is_active'], name='alert_urgency_active_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='alert_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_by', 'created_at'], name='alert_creator_time_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category', 'urgency'], name='alert_cat_urgency_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['user', 'delivered_at'], name='delivery_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['alert', 'channel'], name='delivery_alert_channel_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverylog',
            constraint=models.UniqueConstraint(fields=('alert', 'user'), name='unique_delivery_per_alert_user'),
        ),
    ]
